background = 0xFF313131
base = 0xFF181825
text = 0xFFCDD6F4
alternate_base = 0xFF313244
bright_text = 0xFFF9E2AF

accent = 0xFF62dcdd      # Rosa como cor de destaque
accent_secondary = 0xFF89B4FA  # Azul claro

# Fontes maiores
font_size = 12
small_font_size = 10
h1_size = 22
h2_size = 18
h3_size = 15

font_family = JetBrains Mono Nerd
font_family_monospace = JetBrains Mono Nerd
icon_theme = Kora

# Arredondamentos mais suaves
rounding_large = 10
rounding_small = 10
