[general]
grab_focus = true  # Força foco total do teclado

[cache]
enabled = true     # Mantém cache dos itens usados

[finders]
default_finder = desktop
desktop_prefix = ""      # Sem prefixo para apps do desktop
unicode_prefix = "."     # Prefixo . para emojis/unicode
math_prefix = "="        # Prefixo = para calculadora
font_prefix = "'"        # Prefixo ' para fontes
desktop_launch_prefix = ""
desktop_icons = true    # Mostra ícones nos resultados
desktop_launch_prefix = "hyprctl dispatch exec [workspace] "

[ui]
window_size = 400 260    # Largura Altura
