-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:BOE 0x07CB",
  mode = "1920x1080@59.997",
  position = "0x0",
  scale = 1,
  bitdepth = 10,
  cm = "srgb",
  sdr_eotf = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
